SHOPS = [
  {
    name: "La Trattoria",
    address: "Calle 47 760 La Plata, Argentina",
    email: "trattoria@mail.com",
    phone_number: " 0221-422-6135",
    rating: 4,
    photo: "https://fastly.4sqi.net/img/general/600x600/10642071_qUHgRuywQMdc7XeAlqj2dmr-5nEMc1FTXd2ey-ravHE.jpg",
    user_id: "",
    products: [
      {
        name:"Milanesa de pollo",
        description: "Napolitana recien sacada",
        category: "carnes",
        previous_price: "250",
        unit_price: "125",
        photo: "https://media-cdn.tripadvisor.com/media/photo-s/16/2f/37/e2/photo0jpg.jpg",
      },
      {
        name:"Sorrentinos Jamon y queso",
        description: "Con tuco y mucho queso, para compartir",
        category: "pastas",
        previous_price: "185",
        unit_price: "100",
        photo: "https://www.infobae.com/new-resizer/PexE9VwXrp9ih5u7hZP1CHB9D8Q=/1200x900/filters:format(jpg):quality(85)//s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2019/04/28125657/tratoria-napolinata-mar-del-plata-sorrentinos-161.jpg",
      },
      {
        name:"Bondiola de cerdo",
        description: "bondiola de cerdo a la parrilla",
        category: "carnes",
        previous_price: "380",
        unit_price: "200",
        photo: "https://images.deliveryhero.io/image/pedidosya/products/41514e76-80c5-4ce2-bcab-fedbe98cad9b.jpg?quality=80&width=500",
      },
      {
        name:"Ñoquis con tuco",
        description: "Porcion grande para 2 personas",
        category: "pastas",
        previous_price: "280",
        unit_price: "130",
        photo: "https://t2.rg.ltmcdn.com/es/images/4/2/7/img_noquis_de_papa_con_salsa_de_tomate_60724_600.jpg",
      },
    ]
  },
  {
    name: "Sushi Pop",
    address: "Junín 1242 CABA, Argentina",
    email: "sushi@mail.com",
    phone_number: "011-4821-8131",
    rating: 4,
    photo: "https://centrofranchising.com/wp-content/uploads/2018/09/sushi-pop-logo.jpg",
    user_id: "",
    products: [
      {
        name:"Mix by SushiPop",
        description: "Ultimo Mix del dia super fresco",
        category: "sushi",
        previous_price: "450",
        unit_price: "245",
        photo: "https://res.cloudinary.com/tf-lab/image/upload/w_656,h_368,c_fill,g_auto:subject,q_auto,f_auto/restaurant/41b58f24-4f2a-45dc-92d3-7fc831616291/5980abde-943d-450f-b806-dca572e26feb.jpg",
      },
      {
        name:"24 Piezas",
        description: "El cliente nunca retiro y te estan esperando!!",
        category: "sushi",
        previous_price: "500",
        unit_price: "310",
        photo: "https://media-cdn.tripadvisor.com/media/photo-s/18/e4/37/64/combinado-black.jpg",
      },
      {
        name:"40 Piezas",
        description: "El cliente nunca retiro y te estan esperando, para compartir!!",
        category: "sushi",
        previous_price: "800",
        unit_price: "465",
        photo: "https://latamnoticias.com/wp-content/uploads/2019/05/unnamed-2.jpg",
      },
    ]
  },
  {
    name: "Parrilla Aires Criollos",
    address: "Av Santa Fe 1773 CABA, Argentina",
    email: "parrilla@mail.com",
    phone_number: "011-4472-5561",
    rating: 3,
    photo: "http://www.airescriollos.com.ar/wp-content/uploads/2014/05/parrilla-recoleta-aires-criollos-570x380.jpg",
    user_id: "",
    products: [
      {
        name:"Bife de chorizo especial",
        description: "Con guarnición a a elección (Papas Fritas, Puré de papa o ensalada mixta)",
        category: "carnes",
        previous_price: "590",
        unit_price: "365",
        photo: "https://i.pinimg.com/originals/87/11/22/871122c92d629ce58d19c3b2a299306c.jpg",
      },
      {
        name:"Empanadas",
        description: "Nos estan sobrando empanadas de carne cortada a cuchillo y Jamón y queso (C/U)",
        category: "empanadas",
        previous_price: "100",
        unit_price: "45",
        photo: "https://comidasparaguayas.com/wp-content/uploads/2019/11/empanada-de-carne-paraguaya_700x465.jpg",
      },
      {
        name:"Parrillada para 2 personas",
        description: "Asado, Bondiola, Pollo, Vacío, Morcilla, Chorizo, Chinchulín, Molleja y Riñón Con guarnición a a elección (Papas Fritas, Puré de papa o ensalada mixta)",
        category: "carnes",
        previous_price: "1400",
        unit_price: "850",
        photo: "https://www.circuitogastronomico.com/wp-content/uploads/2019/11/La-Comarca-parrillada-800x600.jpeg",
      },
    ]
  },
  {
    name: "New York Pizza",
    address: "Calle 10 935 La Plata, Argentina",
    email: "pizza@mail.com",
    phone_number: "221224615143",
    rating: 3,
    photo: "http://www.laceliguia.com/wp/wp-content/uploads/cache/images/boutique-de-pizzas/boutique-de-pizzas-1224967337.jpg",
    user_id: "",
    products: [
      {
        name:"Pizza 'Gran New York' ",
        description: "Pizza grande de 8 porciones",
        category: "pizza",
        previous_price: "650",
        unit_price: "320",
        photo: "https://4.bp.blogspot.com/-_Q3d33pmxJ0/WoyymeCctYI/AAAAAAAAAyI/if4Kwu-Lcy8rn-x4O9SLUtF9t0wq9F74wCLcBGAs/s1600/03.jpg",
      },
      {
        name:"Porcion pizza calabreza ",
        description: "Nos estan sobrando empanadas de carne cortada a cuchillo y Jamón y queso (C/U)",
        category: "pizza",
        previous_price: "70",
        unit_price: "45",
        photo: "https://2.bp.blogspot.com/-oFvf4hnig2A/WoyynU89rzI/AAAAAAAAAyc/9xUGlG8NRpMT4SuSpa90pk8KaU75i1q8ACEwYBhgL/s1600/04.jpg",
      },
    ]
  },
  {
    name: "Green Eat",
    address: "Diagonal 74 1618 La Plata, Argentina",
    email: "green@mail.com",
    phone_number: "2244415143",
    rating: 5,
    photo: "https://www.santander.com.ar/banco/wcm/connect/53344df9-7ce5-462c-ae33-a405127db680/img_catalogo_450x435_greeneat.jpg?MOD=AJPERES",
    user_id: "",
    products: [
      {
        name:"Caesar con Pollo",
        description: "Uno de nuestros greatest hits",
        category: "ensaladas",
        previous_price: "450",
        unit_price: "200",
        photo: "https://i.ytimg.com/vi/xaaOAnZRB7Q/maxresdefault.jpg",
      },
      {
        name:"Quinoa Atunada",
        description: "Lomitos de atún + choclo natural + tabule de quínoa y trigo burgol + tomatitos cherries + garbanzos con oliva y pimentón + chauchas, con aderezo de oliva y limón",
        category: "ensaladas",
        previous_price: "360",
        unit_price: "210",
        photo: "https://www.rico.com.ar/upload/products/103/408x650_DSC_0167_.png?1536725752",
      },
      {
        name:"Porto Cheese Burger",
        description: "Hamburguesa de portobellos y lentejas + queso halloumi + tomatitos + cebollita + ketchup raw (receta única) + aderezo de zanahorias",
        category: "sanguches",
        previous_price: "500",
        unit_price: "280",
        photo: "https://www.cocinavital.mx/wp-content/uploads/2018/03/hamburguesa-vegana.jpg",
      },
      {
        name:"Merluza a la plancha",
        description: "Merluza a la plancha con guarnicion a eleccion",
        category: "carnes",
        previous_price: "550",
        unit_price: "450",
        photo: "https://images.deliveryhero.io/image/pedidosya/products/954693-b1d72e2d-dbb5-4153-b8e3-cd2b52705072.jpg?quality=80&width=200",
      },
      {
        name:"Philadelphia Roll",
        description: "6 piezas de sushi (philadelphia roll)",
        category: "sushi",
        previous_price: "550",
        unit_price: "425",
        photo: "https://tiger-corporation-us.com/wp-content/uploads/2019/08/philadelphia-roll-900x600.jpg",
      },
      {
        name:"Gran Mex",
        description: "Bondiola mechada por horas, queso, cilantro, arroz atomatado, pimientos y especias.",
        category: "sanguches",
        previous_price: "380",
        unit_price: "200",
        photo: "https://rico.com.ar/upload/products/222/408x650_Sandwich_Roll%20Gran%20Mex.png?1591805543",
      },
    ]
  },
  {
    name: "Sushi Club",
    address: "Av. Las Heras 2956 CABA, Argentina",
    email: "sushi-club@mail.com",
    phone_number: "0810-222-SUSHI (7874)",
    rating: 4,
    photo: "https://lh5.googleusercontent.com/proxy/pIWJ0O2R6oaN5hqaSsObdbPYt7dbAqj7KlrY3DKuBnz7r6zkUSSelZEoB9yW3ljeh-uu4eS0zueIhPdyRfNtvWz_8NmVofhJ4rumV0EblzrT",
    user_id: "",
    products: [
      {
        name:"Philadelphia Roll (4p)",
        description: "relleno de salmón y queso crema, con sésamo",
        category: "sushi",
        previous_price: "650",
        unit_price: "350",
        photo: "http://www.sushiboom.com.ar/488-large_default/philadelphia.jpg",
      },
      {
        name:"Niguiris de Salmón (6p)",
        description: "finas fetas de salmón sobre arroz",
        category: "sushi",
        previous_price: "700",
        unit_price: "450",
        photo: "https://images.ricardocuisine.com/services/recipes/500x675_7489.jpg?_ga=2.247284164.1944325625.1597178415-462113163.1597178415",
      },
      {
        name:"Combinado SushiClub",
        description: "buenos aires roll, placer real, feel roll, honey roll, philadelphia roll, niguiri de salmón y sashimi de salmón",
        category: "sushi",
        previous_price: "1000",
        unit_price: "650",
        photo: "https://www.sushidag.com.ar/wp-content/uploads/2018/04/jerusalem.jpg",
      },
    ]
  },
   {
    name: "Tea Connection",
    address: "Av. Federico Lacroze 2233 CABA, Argentina",
    email: "lacroze@teaconnection.com.ar",
    phone_number: "(5411) 4779-0490",
    rating: 5,
    photo: "https://wordpress.nogluten.com.ar/wp-content/uploads/2018/09/69488764_10157685982802340_9158788162653257728_n.jpg",
    user_id: "",
    products: [
      {
        name:"Hummus",
        description: "Hummus de garbanzos con pan pita.",
        category: "otros",
        previous_price: "260",
        unit_price: "150",
        photo: "https://images.rappi.com.ar/products/1222454-1596745344643.png?d=400x400&e=webp",
      },
      {
        name:"Bagel de Salmón & Papas",
        description: "Bagel casero con salmón ahumado, palta, rúcula, cream cheese con eneldo, limón. Con papas.",
        category: "sanguches",
        previous_price: "550",
        unit_price: "450",
        photo: "https://images.rappi.com.ar/products/bagel-salmon-1573742051376.png?d=400x400&e=webp",
      },
      {
        name:"Ensalada Caesar con Pollo",
        description: "Ensalada con pechugas de pollo, verdes orgánicos, bastones de queso sardo con croutons, Caesar dressing.",
        category: "ensaladas",
        previous_price: "450",
        unit_price: "200",
        photo: "https://images.rappi.com.ar/products/caesar-1573741995528.png?d=400x400&e=webp",
      },
      {
        name:"Ñoquis de calabaza",
        description: "Ñoquis de calabaza con crema de cabutia, salvia y parmesano.",
        category: "pastas",
        previous_price: "380",
        unit_price: "250",
        photo: "https://images.deliveryhero.io/image/pedidosya/products/3c2bd017-9270-4653-b339-e808cd12597c.jpg?quality=80&width=200",
      },
      {
        name:"Pastel de Papa",
        description: "VEGETARIANO Pastel de papas y vegetales, sin carne",
        category: "otros",
        previous_price: "380",
        unit_price: "200",
        photo: "https://images.rappi.com.ar/products/1131942-1587385854142.jpg?d=400x400&e=webp",
      },
    ]
  },
    {
    name: "Bellagamba",
    address: "Av Rivadavia 2183 CABA, Argentina",
    email: "bella-gamba@mail.com",
    phone_number: "11-4574333",
    rating: 4,
    photo: "https://img.guiaoleo.com.ar/unsafe/938x528/filters:fill(green)/photo_7535_1.jpg-fdd4cd36-f4e4-11e4-be7b-d3500e263ce1_s0.jpg",
    user_id: "",
    products: [
      {
        name:"Empanadas JyQ",
        description: "Empanadas de jamon y queso al horno ",
        category: "empanadas",
        previous_price: "650",
        unit_price: "350",
        photo: "https://lareceta.com.ar/uploads/notas/phpzxe2GY.jpg",
      },
      {
        name:"Filet de merluza",
        description: "Filet de merluza con papas hervidas ",
        category: "carnes",
        previous_price: "360",
        unit_price: "250",
        photo: "https://images.deliveryhero.io/image/pedidosya/products/473654-ee96a924-35fd-417f-8f0a-dea5b866132a.jpg?quality=80&width=500",
      },
      {
        name:"Spaghetti",
        description: "Spaghettis a la carbonara",
        category: "pastas",
        previous_price: "552",
        unit_price: "350",
        photo: "https://images.deliveryhero.io/image/pedidosya/products/10b71c47-45f3-47a3-a313-b12267af0864.jpg?quality=80&width=500",
      },
      {
        name:"Ojo de Bife",
        description: "Ojo de bife viene con chimichurri",
        category: "carnes",
        previous_price: "700",
        unit_price: "450",
        photo: "https://images.rappi.com.ar/products/193012-1532461177.png?d=400x400&e=webp",
      },
      {
        name:"Pizza calabreza",
        description: "Masa de pizza, salsa, queso muzzarella y longaniza",
        category: "pizza",
        previous_price: "450",
        unit_price: "350",
        photo: "https://img-global.cpcdn.com/recipes/004c275376ef9795/640x640sq70/photo.jpg",
      },
    ]
  },
    {
    name: " Panaderia El condor",
    address: "Av. Lope de Vega 1864 CABA, Argentina",
    email: "elcondor@mail.com",
    phone_number: "+541145670493",
    rating: 3,
    photo: "https://10619-2.s.cdn12.com/rests/original/102_503528697.jpg",
    user_id: "",
    products: [
            {
              name:"Facuturas",
              description: "docena de facturas surtidas",
              category: "panaderia",
              previous_price: "280",
              unit_price: "160",
              photo: "https://upload.wikimedia.org/wikipedia/commons/7/72/VariedadDeFacturas1.jpg",
            },
            {
              name:"Pan mignon",
              description: "1 kg de pan mignon",
              category: "panaderia",
              previous_price: "150",
              unit_price: "60",
              photo: "https://www.johaprato.com/files/styles/flexslider_full/public/mignon.jpg?itok=Vl08dMPl",
            },
            {
              name:"Alfajores de maicena",
              description: "12 alfajores de maicena",
              category: "panaderia",
              previous_price: "750",
              unit_price: "500",
              photo: "https://secureservercdn.net/198.71.233.141/d66.2e2.myftpupload.com/wp-content/uploads/2017/07/Alf-maicena-1-Large.jpg?time=1597239600",
      },
    ]
  },
    {
    name: " El capataz",
    address: "Maipu 529 CABA, Argentina",
    email: "elcapataz@mail.com",
    phone_number: "+54114573331",
    rating: 2,
    photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS4yeOys3afvidpZ8gA2VfaLZzZcuJDNFhTzw&usqp=CAU",
    user_id: "",
    products: [
            {
              name:"Ñoquis de papa",
              description: "Ñoquis de papa con crema",
              category: "pastas",
              previous_price: "299",
              unit_price: "150",
              photo: "https://images.clarin.com/2018/06/19/HJS8-kvW7_340x340__1.jpg",
            },
            {
              name:"Asado de tira",
              description: "Asado de tira con guarnicion a eleccion",
              category: "carnes",
              previous_price: "485",
              unit_price: "300",
              photo: "https://images.deliveryhero.io/image/pedidosya/products/316505-4fe3ca9c-5433-49be-8721-da3e623658be.jpg?quality=80&width=200",
            },
            {
              name:"Spaghettis al huevo",
              description: "Spaghettis al huevo con crema",
              category: "pastas",
              previous_price: "299",
              unit_price: "199",
              photo: "https://images.deliveryhero.io/image/pedidosya/products/312955-65229063-9022-42fb-b790-d5da07cdeda2.jpg?quality=80&width=500",
            },
    ]
  },
    {
      name: "Panaderia La Argentina",
    address: "Paraguay 1399 CABA, Argentina",
    email: "laargentina@mail.com",
    phone_number: "11-4519-8522",
    rating: 5,
    photo: "http://clargentina.com.ar/img/nos02.jpg",
    user_id: "",
    products: [
      {
        name:"Medialunas de manteca",
        description: "2 docenas de medialunas de mantecas hechas en el dia",
        category: "panaderia",
        previous_price: "720",
        unit_price: "500",
        photo: "https://images.deliveryhero.io/image/pedidosya/products/421882-eab21829-b21e-40b4-91df-e0f33e09a5f6.jpg?quality=80&width=200",
      },
      {
        name:"Sandwiches de miga",
        description: "Sandwiches de miga de jamon y queso (15 un)",
        category: "sanguches",
        previous_price: "450",
        unit_price: "250",
        photo: "https://images.deliveryhero.io/image/pedidosya/products/439553-76ab24cc-0708-4452-b4ef-713cd766b520.jpg?quality=80&width=500",
      },
      {
        name:"Torta Rogel",
        description: "deliciosa torta rogel con dulce de leche y merengue italiano",
        category: "otros",
        previous_price: "1000",
        unit_price: "650",
        photo: "https://http2.mlstatic.com/D_NQ_NP_112725-MLA25491928779_042017-O.webp",
      },
    ]
  }
]

