SHOPS = [
  {
    name: "La Trattoria",
    address: "Calle 47 760 La Plata, Argentina",
    email: "trattoria@mail.com",
    phone_number: " 0221-422-6135",
    photo: "https://fastly.4sqi.net/img/general/600x600/10642071_qUHgRuywQMdc7XeAlqj2dmr-5nEMc1FTXd2ey-ravHE.jpg",
    user_id: "",
    products: [
      {
        name:"Milanesa de pollo",
        description: "Napolitana recien sacada",
        category: "sanguches",
        previous_price: "250",
        unit_price: "125",
        photo: "https://media-cdn.tripadvisor.com/media/photo-s/16/2f/37/e2/photo0jpg.jpg",
      },
      {
        name:"Sorrentinos Jamon y queso",
        description: "Con tuco y mucho queso, para compartir",
        category: "pastas",
        previous_price: "185",
        unit_price: "100",
        photo: "https://www.infobae.com/new-resizer/PexE9VwXrp9ih5u7hZP1CHB9D8Q=/1200x900/filters:format(jpg):quality(85)//s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2019/04/28125657/tratoria-napolinata-mar-del-plata-sorrentinos-161.jpg",
      },
      {
        name:"Ñoquis con tuco",
        description: "Porcion grande para 2 personas",
        category: "pastas",
        previous_price: "280",
        unit_price: "130",
        photo: "https://t2.rg.ltmcdn.com/es/images/4/2/7/img_noquis_de_papa_con_salsa_de_tomate_60724_600.jpg",
      },
    ]
  },
  {
    name: "Sushi Pop",
    address: "Junín 1242 CABA, Argentina",
    email: "sushi@mail.com",
    phone_number: "011-4821-8131",
    photo: "https://centrofranchising.com/wp-content/uploads/2018/09/sushi-pop-logo.jpg",
    user_id: "",
    products: [
      {
        name:"Mix by SushiPop",
        description: "Ultimo Mix del dia super fresco",
        category: "sushi",
        previous_price: "450",
        unit_price: "245",
        photo: "https://res.cloudinary.com/tf-lab/image/upload/w_656,h_368,c_fill,g_auto:subject,q_auto,f_auto/restaurant/41b58f24-4f2a-45dc-92d3-7fc831616291/5980abde-943d-450f-b806-dca572e26feb.jpg",
      },
      {
        name:"24 Piezas",
        description: "El cliente nunca retiro y te estan esperando!!",
        category: "sushi",
        previous_price: "500",
        unit_price: "310",
        photo: "https://media-cdn.tripadvisor.com/media/photo-s/18/e4/37/64/combinado-black.jpg",
      },
      {
        name:"40 Piezas",
        description: "El cliente nunca retiro y te estan esperando, para compartir!!",
        category: "sushi",
        previous_price: "800",
        unit_price: "465",
        photo: "https://latamnoticias.com/wp-content/uploads/2019/05/unnamed-2.jpg",
      },
    ]
  },
  {
    name: "Parrilla Aires Criollos",
    address: "Av Santa Fe 1773 CABA, Argentina",
    email: "parrilla@mail.com",
    phone_number: "011-4472-5561",
    photo: "http://www.airescriollos.com.ar/wp-content/uploads/2017/08/logo1.png",
    user_id: "",
    products: [
      {
        name:"Bife de chorizo especial",
        description: "Con guarnición a a elección (Papas Fritas, Puré de papa o ensalada mixta)",
        category: "asado",
        previous_price: "590",
        unit_price: "365",
        photo: "https://i.pinimg.com/originals/87/11/22/871122c92d629ce58d19c3b2a299306c.jpg",
      },
      {
        name:"Empanadas",
        description: "Nos estan sobrando empanadas de carne cortada a cuchillo y Jamón y queso (C/U)",
        category: "empanadas",
        previous_price: "100",
        unit_price: "45",
        photo: "https://comidasparaguayas.com/wp-content/uploads/2019/11/empanada-de-carne-paraguaya_700x465.jpg",
      },
      {
        name:"Parrillada para 2 personas",
        description: "Asado, Bondiola, Pollo, Vacío, Morcilla, Chorizo, Chinchulín, Molleja y Riñón Con guarnición a a elección (Papas Fritas, Puré de papa o ensalada mixta)",
        category: "asado",
        previous_price: "1400",
        unit_price: "850",
        photo: "https://www.circuitogastronomico.com/wp-content/uploads/2019/11/La-Comarca-parrillada-800x600.jpeg",
      },
    ]
  },
  {
    name: "New York Pizza",
    address: "Calle 10 935 La Plata, Argentina",
    email: "pizza@mail.com",
    phone_number: "221224615143",
    photo: "http://www.laceliguia.com/wp/wp-content/uploads/cache/images/boutique-de-pizzas/boutique-de-pizzas-1224967337.jpg",
    user_id: "",
    products: [
      {
        name:"Pizza 'Gran New York' ",
        description: "Pizza grande de 8 porciones",
        category: "pizza",
        previous_price: "650",
        unit_price: "320",
        photo: "https://4.bp.blogspot.com/-_Q3d33pmxJ0/WoyymeCctYI/AAAAAAAAAyI/if4Kwu-Lcy8rn-x4O9SLUtF9t0wq9F74wCLcBGAs/s1600/03.jpg",
      },
      {
        name:"Porcion pizza calabreza ",
        description: "Nos estan sobrando empanadas de carne cortada a cuchillo y Jamón y queso (C/U)",
        category: "pizza",
        previous_price: "70",
        unit_price: "45",
        photo: "https://2.bp.blogspot.com/-oFvf4hnig2A/WoyynU89rzI/AAAAAAAAAyc/9xUGlG8NRpMT4SuSpa90pk8KaU75i1q8ACEwYBhgL/s1600/04.jpg",
      },
    ]
  },
  {
    name: "Green Eat",
    address: "Diagonal 74 1618 La Plata, Argentina",
    email: "green@mail.com",
    phone_number: "2244415143",
    photo: "https://www.santander.com.ar/banco/wcm/connect/53344df9-7ce5-462c-ae33-a405127db680/img_catalogo_450x435_greeneat.jpg?MOD=AJPERES",
    user_id: "",
    products: [
      {
        name:"Caesar con Pollo",
        description: "Uno de nuestros greatest hits",
        category: "asado",
        previous_price: "450",
        unit_price: "200",
        photo: "https://i.ytimg.com/vi/xaaOAnZRB7Q/maxresdefault.jpg",
      },
      {
        name:"Quinoa Atunada",
        description: "Lomitos de atún + choclo natural + tabule de quínoa y trigo burgol + tomatitos cherries + garbanzos con oliva y pimentón + chauchas, con aderezo de oliva y limón",
        category: "ensaladas",
        previous_price: "360",
        unit_price: "210",
        photo: "https://www.rico.com.ar/upload/products/103/408x650_DSC_0167_.png?1536725752",
      },
      {
        name:"Porto Cheese Burger",
        description: "Hamburguesa de portobellos y lentejas + queso halloumi + tomatitos + cebollita + ketchup raw (receta única) + aderezo de zanahorias",
        category: "sanguches",
        previous_price: "500",
        unit_price: "280",
        photo: "https://www.cocinavital.mx/wp-content/uploads/2018/03/hamburguesa-vegana.jpg",
      },
      {
        name:"Gran Mex",
        description: "Bondiola mechada por horas, queso, cilantro, arroz atomatado, pimientos y especias.",
        category: "sanguches",
        previous_price: "380",
        unit_price: "200",
        photo: "https://rico.com.ar/upload/products/222/408x650_Sandwich_Roll%20Gran%20Mex.png?1591805543",
      },
    ]
  },
  {
    name: "Sushi Club",
    address: "Av. Las Heras 2956 CABA, Argentina",
    email: "sushi-club@mail.com",
    phone_number: "0810-222-SUSHI (7874)",
    photo: "https://www.numeral11.com/wp-content/uploads/2016/10/sushi-club-logo-e1497406187812.jpg",
    user_id: "",
    products: [
      {
        name:"Philadelphia Roll (4p)",
        description: "relleno de salmón y queso crema, con sésamo",
        category: "sushi",
        previous_price: "650",
        unit_price: "350",
        photo: "http://www.sushiboom.com.ar/488-large_default/philadelphia.jpg",
      },
      {
        name:"Niguiris de Salmón (6p)",
        description: "finas fetas de salmón sobre arroz",
        category: "sushi",
        previous_price: "700",
        unit_price: "450",
        photo: "https://images.ricardocuisine.com/services/recipes/500x675_7489.jpg?_ga=2.247284164.1944325625.1597178415-462113163.1597178415",
      },
      {
        name:"Combinado SushiClub (15p)",
        description: "buenos aires roll, placer real, feel roll, honey roll, philadelphia roll, niguiri de salmón y sashimi de salmón",
        category: "sushi",
        previous_price: "1000",
        unit_price: "650",
        photo: "https://www.sushidag.com.ar/wp-content/uploads/2018/04/jerusalem.jpg",
      },
    ]
  },
]
